
ALTER TABLE public.admissions ADD CONSTRAINT admissions_bed_id_fkey FOREIGN KEY (bed_id) REFERENCES public.beds(id) ON DELETE SET NULL;
ALTER TABLE public.admissions ADD CONSTRAINT admissions_encounter_id_fkey FOREIGN KEY (encounter_id) REFERENCES public.encounters(id) ON DELETE SET NULL;
ALTER TABLE public.admissions ADD CONSTRAINT admissions_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id) ON DELETE CASCADE;
ALTER TABLE public.admissions ADD CONSTRAINT admissions_ward_id_fkey FOREIGN KEY (ward_id) REFERENCES public.wards(id) ON DELETE SET NULL;
ALTER TABLE public.appointments ADD CONSTRAINT appointments_encounter_id_fkey FOREIGN KEY (encounter_id) REFERENCES public.encounters(id) ON DELETE SET NULL;
ALTER TABLE public.appointments ADD CONSTRAINT appointments_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id) ON DELETE CASCADE;
ALTER TABLE public.beds ADD CONSTRAINT beds_ward_id_fkey FOREIGN KEY (ward_id) REFERENCES public.wards(id) ON DELETE CASCADE;
ALTER TABLE public.clinical_notes ADD CONSTRAINT clinical_notes_admission_id_fkey FOREIGN KEY (admission_id) REFERENCES public.admissions(id) ON DELETE CASCADE;
ALTER TABLE public.clinical_notes ADD CONSTRAINT clinical_notes_encounter_id_fkey FOREIGN KEY (encounter_id) REFERENCES public.encounters(id) ON DELETE CASCADE;
ALTER TABLE public.deliveries ADD CONSTRAINT deliveries_stock_item_id_fkey FOREIGN KEY (stock_item_id) REFERENCES public.stock_items(id) ON DELETE SET NULL;
ALTER TABLE public.encounter_amendments ADD CONSTRAINT encounter_amendments_encounter_id_fkey FOREIGN KEY (encounter_id) REFERENCES public.encounters(id) ON DELETE CASCADE;
ALTER TABLE public.encounter_diagnoses ADD CONSTRAINT encounter_diagnoses_encounter_id_fkey FOREIGN KEY (encounter_id) REFERENCES public.encounters(id) ON DELETE CASCADE;
ALTER TABLE public.encounter_indicator_tags ADD CONSTRAINT encounter_indicator_tags_encounter_id_fkey FOREIGN KEY (encounter_id) REFERENCES public.encounters(id) ON DELETE CASCADE;
ALTER TABLE public.encounter_room_visits ADD CONSTRAINT encounter_room_visits_encounter_id_fkey FOREIGN KEY (encounter_id) REFERENCES public.encounters(id) ON DELETE CASCADE;
ALTER TABLE public.encounter_room_visits ADD CONSTRAINT encounter_room_visits_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.rooms(id) ON DELETE CASCADE;
ALTER TABLE public.encounters ADD CONSTRAINT encounters_current_room_id_fkey FOREIGN KEY (current_room_id) REFERENCES public.rooms(id) ON DELETE SET NULL;
ALTER TABLE public.encounters ADD CONSTRAINT encounters_insurance_provider_id_fkey FOREIGN KEY (insurance_provider_id) REFERENCES public.insurance_providers(id) ON DELETE SET NULL;
ALTER TABLE public.encounters ADD CONSTRAINT encounters_next_room_id_fkey FOREIGN KEY (next_room_id) REFERENCES public.rooms(id) ON DELETE SET NULL;
ALTER TABLE public.encounters ADD CONSTRAINT encounters_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id) ON DELETE CASCADE;
ALTER TABLE public.invoice_line_items ADD CONSTRAINT invoice_line_items_encounter_id_fkey FOREIGN KEY (encounter_id) REFERENCES public.encounters(id) ON DELETE SET NULL;
ALTER TABLE public.invoice_line_items ADD CONSTRAINT invoice_line_items_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id) ON DELETE CASCADE;
ALTER TABLE public.invoice_payments ADD CONSTRAINT invoice_payments_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id) ON DELETE CASCADE;
ALTER TABLE public.invoices ADD CONSTRAINT invoices_encounter_id_fkey FOREIGN KEY (encounter_id) REFERENCES public.encounters(id) ON DELETE SET NULL;
ALTER TABLE public.invoices ADD CONSTRAINT invoices_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id) ON DELETE CASCADE;
ALTER TABLE public.lab_test_catalog ADD CONSTRAINT lab_test_catalog_target_room_id_fkey FOREIGN KEY (target_room_id) REFERENCES public.rooms(id) ON DELETE SET NULL;
ALTER TABLE public.machine_logs ADD CONSTRAINT machine_logs_machine_id_fkey FOREIGN KEY (machine_id) REFERENCES public.machines(id) ON DELETE CASCADE;
ALTER TABLE public.moh_report_line_items ADD CONSTRAINT moh_report_line_items_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.moh_report_templates(id) ON DELETE CASCADE;
ALTER TABLE public.moh_report_submissions ADD CONSTRAINT moh_report_submissions_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.moh_report_templates(id) ON DELETE CASCADE;
ALTER TABLE public.patient_registrations_legacy ADD CONSTRAINT patient_registrations_current_room_id_fkey FOREIGN KEY (current_room_id) REFERENCES public.rooms(id) ON DELETE SET NULL;
ALTER TABLE public.patient_registrations_legacy ADD CONSTRAINT patient_registrations_insurance_provider_id_fkey FOREIGN KEY (insurance_provider_id) REFERENCES public.insurance_providers(id) ON DELETE SET NULL;
ALTER TABLE public.patient_registrations_legacy ADD CONSTRAINT patient_registrations_next_room_id_fkey FOREIGN KEY (next_room_id) REFERENCES public.rooms(id) ON DELETE SET NULL;
ALTER TABLE public.prescriptions ADD CONSTRAINT prescriptions_stock_item_id_fkey FOREIGN KEY (stock_item_id) REFERENCES public.stock_items(id) ON DELETE SET NULL;
ALTER TABLE public.radiology_orders ADD CONSTRAINT radiology_orders_catalog_id_fkey FOREIGN KEY (catalog_id) REFERENCES public.lab_test_catalog(id) ON DELETE SET NULL;
ALTER TABLE public.radiology_orders ADD CONSTRAINT radiology_orders_encounter_id_fkey FOREIGN KEY (encounter_id) REFERENCES public.encounters(id) ON DELETE SET NULL;
ALTER TABLE public.radiology_orders ADD CONSTRAINT radiology_orders_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id) ON DELETE CASCADE;
ALTER TABLE public.radiology_results ADD CONSTRAINT radiology_results_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.radiology_orders(id) ON DELETE CASCADE;
ALTER TABLE public.room_indicator_map ADD CONSTRAINT room_indicator_map_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.rooms(id) ON DELETE CASCADE;
ALTER TABLE public.stock_movements ADD CONSTRAINT stock_movements_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.stock_items(id) ON DELETE CASCADE;
ALTER TABLE public.user_room_access ADD CONSTRAINT user_room_access_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.rooms(id) ON DELETE CASCADE;
